server:
  port: 8765

spring:
  application:
    name: Consumer

  devtools:
    restart:
      enabled: true
      trigger-file: devtools.tg


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false


eureka:
  client:
    service-url:
      defaultZone: http://192.168.43.181:7788/eureka/
  instance:
    prefer-ip-address: true

      feign:
        hystrix:
          enabled: true
